[[target]]
name = "train-to-ciampino"
assets = []

[target.metadata]
name = "Train to Ciampino"
author = "Giorgio Pomettini"
bundle_id = "com.pomettini.ggj2024"
version = "0.1"
image_path = "assets/launcher"
